version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "00:00"
  open-pull-requests-limit: 10
  assignees:
  - kagamichan
  ignore:
  - dependency-name: react-i18next
    versions:
    - 11.8.12
  - dependency-name: i18next
    versions:
    - 20.1.0
  - dependency-name: "@types/webpack"
    versions:
    - 5.0.0
  - dependency-name: twin.macro
    versions:
    - 2.1.0
    - 2.2.0
    - 2.2.2
    - 2.2.3
  - dependency-name: typescript
    versions:
    - 3.9.9
  - dependency-name: puppeteer
    versions:
    - 7.0.1
