name: Build and test

on:
  push:
    branches-ignore:
      - release

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use LTS node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Installing puppeteer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm1

      - uses: pnpm/action-setup@v3

      - name: Get pnpm cache directory path
        id: nodejs-deps-cache-dir-path
        run: echo "::set-output name=dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Caching Node.js dependencies
        id: nodejs-deps-cache
        with:
          path: ${{ steps.nodejs-deps-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-pnpm-v1-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-v1

      - uses: actions/cache@v3
        name: Caching Gatsby
        with:
          path: .cache
          key: ${{ runner.os }}-gatsby-cache-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-gatsby-cache

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test

      - name: Deploying master branch
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm deploy
