name: Build and test

on:
  push:
    branches-ignore:
      - release

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use LTS node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - uses: pnpm/action-setup@v3

      - name: Get pnpm cache directory path
        id: nodejs-deps-cache-dir-path
        run: echo "::set-output name=dir::$(pnpm store path)"

      - uses: actions/cache@v4
        name: Caching Node.js dependencies
        id: nodejs-deps-cache
        with:
          path: ${{ steps.nodejs-deps-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-pnpm-v1-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-v1

      - uses: actions/cache@v4
        name: Caching Gatsby
        with:
          path: .cache
          key: ${{ runner.os }}-gatsby-cache-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-gatsby-cache

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Deploying master branch
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm run deploy
